### ISSUE TITLE
Error: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by MurzNN** [Thomas1664/ts-node-template#1]
I'm trying to initialize and launch this project via following commands:
```
$  git clone https://github.com/Thomas1664/ts-node-template.git
$ cd ts-node-template
$ npm init -y
$ npm i -D typescript ts-node
$ node ./index.ts
```
But, as result, I've got an error:
```
(node:4132010) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/user/ts-node-template/index.ts:1
import http from 'http'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```
How to fix this problem?

**Comment by MurzNN** [comment]
If I'm trying to use `ts-node` launcher, I've got another error:
```
$ ts-node ./index.ts 

.../node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
index.ts:1:18 - error TS2307: Cannot find module 'http' or its corresponding type declarations.

1 import http from 'http'
                   ~~~~~~
index.ts:5:18 - error TS7006: Parameter 'req' implicitly has an 'any' type.

5 function handler(req, res) {
                   ~~~
index.ts:5:23 - error TS7006: Parameter 'res' implicitly has an 'any' type.

5 function handler(req, res) {
                        ~~~

    at createTSError (.../node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (.../node_modules/ts-node/src/index.ts:517:19)
    at getOutput (.../node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (.../node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (.../node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (.../node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
```

**Comment by Thomas1664** [comment]
1. You used `node` instead of `ts-node` to launch the script
2. You missed the command `npm i -g typescript ts-node`

**Comment by MurzNN** [comment]
Hmm, why I need to install `typescript` and `ts-node` globally, if I already installed them locally?

**Comment by Thomas1664** [comment]
Otherwise `ts-node` is not recognized outside a node environment. Try it out and type `ts-node` in cmd.

**Comment by MurzNN** [comment]
So we need only the `ts-node` installed globally or use `npx`, right? I already have it, see https://github.com/Thomas1664/ts-node-template/issues/1#issuecomment-995556929
And seems we also need to install `@types/node` via command `npm i -D @types/node`.
